apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
spec:
  description: Application services

  sourceRepos:
    - 'https://github.com/my-git/k8s.git'

  destinations:
    - namespace: '*-dev'
      server: https://kubernetes.default.svc
    - namespace: '*-stg'
      server: https://kubernetes.default.svc
    - namespace: '*-prod'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist: []