provider:
  name: aws

aws:
  region: ap-northeast-2

domainFilters:
  - myhosting

txtOwnerId: platform
policy: sync

serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::myaccount:role/external-dns

sources:
  - ingress

image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.19.0

logLevel: info

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi